### PR TITLE
veloCV was added to the integrations

### PR DESCRIPTION
**Pull request by fballiano**
velocv.com is a new resume creator website which is deeply based on jsonResume and on the fact that the user is always the owner of his data (users can download their jsonresume at any time).

also velocv features an advanced linkedin import based on chrome/firefox extensions.

thus actually you can convert your linkedin profile (multilanguage profiles are supported) in jsonresumes with just a few clicks.

### CODE REVIEW

**Comment by thomasdavis** [comment]
Thanks @fballiano, Looks awesome. Think you could add an image in another pull request.

**Comment by fballiano** [comment]
Thanks a lot @thomasdavis!

Question: which image are you talking about? Instead of the favicon?

:-)

**Comment by thomasdavis** [comment]
Nevermind, you did. I think the proportions are off though. Messes up the alignment.

**Comment by fballiano** [comment]
so sorry, there's a "closing div" missing, going to create a new PR right now, sorry again!

**Pull request merged**
