### PR TITLE
#44 - Rename website as url

### PR DESCRIPTION
**Pull request by XuluWarrior**

### CODE REVIEW

**Comment by felipecrs** [comment]
This is a change from schema 0.0.0 to schema v1.0.0. I believe you should update not only the "website" fields.

**Comment by XuluWarrior** [comment]
To be honest I can't remember why I created this PR.  It's almost two years ago now.

I think it may have been because the example "Alan Doe" [resume.json](https://github.com/XuluWarrior/jsonresume-theme-kards/blob/master/example-resume.json) I based my themes on uses `url` rather than `website` as used in the default resume.json.  I then probably checked the schema being validated against and saw the discrepancy. 

I see that because of the use of `"additionalProperties": true` in the schema it will allow both `website` and `url` but it is `url` which will be validated as a uri.

As `resume-cli` (now) depends on `resume-schema@0.0.18` the resume.json generated by `resume init` and the example json documented in the website should reflect that particular version of `schema.json`.

Having taken another look, I see that `picture` has also been replaced with `image`.

At this point, I don't feel I know enough to say what needs to change in which projects to make it all internally consistent.

**Comment by felipecrs** [comment]
More things were changed... `url` was introduced for `education`, we also have `projects`. It would be good to have a sync between all the projects.

**Comment by XuluWarrior** [comment]
I'm happy to assist in some way but it feels like I'm missing context.  The project seems to move in fits and starts.  And I don't have a clear feeling of where it is heading.

**Comment by felipecrs** [comment]
As far as I know, the core of the project is the [schema](https://github.com/jsonresume/resume-schema). It was updated to 1.0.0 with some changes, but `resume-cli` and `resume-website` wasn't yet updated to reflect those changes.

**Comment by rbardini** [comment]
`resume-cli` has been updated to support the latest `resume-schema` version, including a new default theme compatible with it. It hasn't been released to npm yet though, but it should once https://github.com/jsonresume/resume-cli/pull/377 is merged.

**Comment by felipecrs** [comment]
> `resume-cli` has been updated to support the latest `resume-schema` version, including a new default theme compatible with it. It hasn't been released to npm yet though, but it should once [jsonresume/resume-cli#377](https://github.com/jsonresume/resume-cli/pull/377) is merged.

That's awesome!

**Pull request closed without merging**
