### PR TITLE
Update language's keys to match actual schema

### PR DESCRIPTION
**Pull request by svenluijten**
[the actual schema](https://github.com/jsonresume/resume-schema/blob/v1.0.0/schema.json#L317-L335)

### CODE REVIEW

**Comment by stp-ip** [comment]
The website doesn't use v1 and therefore this change is most likely a bit premature.
The general notion right now is to finish the schema first and then migrate everything over as there might be intermediate solutions and duplicating work doesn't seem perfect.

Thanks for the contribution and we would definitely love to see more contributions in the future. There are some open PR ready issues for the schema itself.

**Comment by svenluijten** [comment]
Right, I agree that duplicating work isn't perfect, but shouldn't the documentation of the schema on the website match the latest themes' requirements? We could version the docs to make a better distinction between version 0.* and 1.* of the schema.

**Comment by stp-ip** [comment]
The v1 schema is not even in beta state and therefore no documentation needs it to match yet.

When we finalize v1, we can move the docs. Having old docs for v0 seems unnecessary as v0 said via semver unfinished.

**Comment by svenluijten** [comment]
> The v1 schema is not even in beta state
Then that should be fixed in the `resume-cli` package. I pulled it in yesterday, expecting to get the latest stable release but I got the beta version instead?

**Comment by svenluijten** [comment]
Actually, that change should probably be made in the themes that ship with the `resume-cli` package, not the cli itself.

**Comment by stp-ip** [comment]
I'm not too familiar with the tooling for cli, but I assume using latest here https://github.com/jsonresume/resume-cli/blob/master/package.json#L35 and the recent change of the default branch to v1 might be the issue. The latest stable of the schema is still the master branch at: https://github.com/jsonresume/resume-schema/tree/master.

cc. @thomasdavis

**Comment by svenluijten** [comment]
Right. What I think is happening though is that some of the theme creators updated their themes to the new format too quickly, effectively outdating the current documentation on the website.

FWIW, I noticed this issue when using the Flat theme.

**Comment by stp-ip** [comment]
We can't really do much about it, besides trying to make v1 ready to be the stable replacement. All help appreciated ;)

**Pull request closed without merging**
